2Python script encountered an error. Exit code: 1
Result JSON:
VE:\ISEL\Projeto\uag-prediction-system\ModuloTreino(1).py:55: SettingWithCopyWarning: 
CA value is trying to be set on a copy of a slice from a DataFrame.
8Try using .loc[row_indexer,col_indexer] = value instead

‹See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
(  df['MA_3a5'] = MediaMovel(df, -5, -2)
VE:\ISEL\Projeto\uag-prediction-system\ModuloTreino(1).py:56: SettingWithCopyWarning: 
CA value is trying to be set on a copy of a slice from a DataFrame.
8Try using .loc[row_indexer,col_indexer] = value instead

‹See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
(  df['MA_3a9'] = MediaMovel(df, -9, -2)
VE:\ISEL\Projeto\uag-prediction-system\ModuloTreino(1).py:26: SettingWithCopyWarning: 
CA value is trying to be set on a copy of a slice from a DataFrame.
8Try using .loc[row_indexer,col_indexer] = value instead

‹See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
*  df['date'] = pd.to_datetime(df['date'])
VE:\ISEL\Projeto\uag-prediction-system\ModuloTreino(1).py:57: SettingWithCopyWarning: 
CA value is trying to be set on a copy of a slice from a DataFrame.
8Try using .loc[row_indexer,col_indexer] = value instead

‹See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DayType'] = DayType(df)
VE:\ISEL\Projeto\uag-prediction-system\ModuloTreino(1).py:58: SettingWithCopyWarning: 
CA value is trying to be set on a copy of a slice from a DataFrame.
8Try using .loc[row_indexer,col_indexer] = value instead

‹See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
'  df['minValue'] = df_temp['minValue']
VE:\ISEL\Projeto\uag-prediction-system\ModuloTreino(1).py:59: SettingWithCopyWarning: 
CA value is trying to be set on a copy of a slice from a DataFrame.
8Try using .loc[row_indexer,col_indexer] = value instead

‹See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
'  df['maxValue'] = df_temp['maxValue']
#Traceback (most recent call last):
X  File "E:\ISEL\Projeto\uag-prediction-system\ModuloTreino(1).py", line 65, in <module>
'    reg = LinearRegression().fit(X, Y)
'          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
w  File "C:\Users\joaop\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_base.py", line 648, in fit
     X, y = self._validate_data(
            ^^^^^^^^^^^^^^^^^^^^
t  File "C:\Users\joaop\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py", line 584, in _validate_data
+    X, y = check_X_y(X, y, **check_params)
+           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|  File "C:\Users\joaop\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py", line 1106, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
}  File "C:\Users\joaop\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py", line 931, in check_array
    raise ValueError(
nValueError: Found array with 0 sample(s) (shape=(0, 4)) while a minimum of 1 is required by LinearRegression.

